name: Deploy to Ubuntu VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create .ssh directory
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh

    - name: Add kriesoft.com to known_hosts
      run: |
        ssh-keyscan -H kriesoft.com >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Setup SSH Agent with passphrase
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        eval $(ssh-agent -s)
        echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add private_key.pem
        ssh-add -l  # Print loaded keys for debugging
        rm private_key.pem

    - name: Test SSH connection
      run: |
        ssh ubuntu@kriesoft.com "echo SSH connection successful"
