name: Deploy to Ubuntu VM

on:
  push:
    branches:
      - main

env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create .ssh directory
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh

    - name: Add kriesoft.com to known_hosts
      run: |
        ssh-keyscan -H kriesoft.com >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Setup SSH with passphrase
      env:
        SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        echo "echo $SSH_PASSPHRASE" > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null

    - name: Configure Git Safe Directory
      run: |
        ssh ubuntu@kriesoft.com "git config --global --add safe.directory /var/www/virtual-study-group"

    - name: Test SSH connection
      run: |
        ssh ubuntu@kriesoft.com "echo SSH connection successful"

    - name: Deploy to VM
      run: |
        ssh ubuntu@kriesoft.com "cd /var/www/virtual-study-group && git pull && npm ci && npm run build && pm2 reload all || exit 1"
