name: Deploy to Ubuntu VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create .ssh directory
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh

    - name: Add kriesoft.com to known_hosts
      run: |
        # Add all relevant host keys for kriesoft.com
        ssh-keyscan -H kriesoft.com >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VM
      run: |
        ssh ubuntu@kriesoft.com "cd /var/www/virtual-study-group && git pull && npm install && pm2 restart all"
